### ISSUE TITLE
Broken Images In Different Categories

### ISSUE THREAD

**Issue by btindell** [lsuits/grade_breakdown#6]
Hello,

I ran into a couple issues on Moodle 2.6 with broken images with the categories of Course Total, Homework, and Quizzes. When selecting on a range, a page pops up where each student that is in that range is listed. The right most column there should be an image there enabling the user to edit that student's score. However, this is where the issue lies. In Chrome/Safari, there is a broken image listed there. In Firefox, there is just the word "Edit" that is un-clickable. Please see attached pictures for reference. 

Thank you,

Ben Tindell

![safari](https://cloud.githubusercontent.com/assets/7874245/3752257/055c0bf8-1806-11e4-8d15-1e6d628e0104.png)
![firefox](https://cloud.githubusercontent.com/assets/7874245/3752256/055bde26-1806-11e4-9271-fa2fa192cc29.png)
![chrome](https://cloud.githubusercontent.com/assets/7874245/3752255/055b8430-1806-11e4-8724-726b53d2d173.png)

**Comment by rrusso** [comment]
The plugin uses the theme's /i/edit icon. If you don't have one, it's not the fault of this plugin as it's called elsewhere.
