### ISSUE TITLE
Error message from get_role_users in Moodle 2.8

### ISSUE THREAD

**Issue by colin-umn** [lsuits/grade_breakdown#8]
We get the following error message when using this plugin in Moodle 2.8.

[Tue Jan 27 13:45:03.605696 2015] [:error] [pid 48160] [client 127.0.0.1:53388] PHP Notice:  get_role_users() without specifying one single roleid needs to be called prefixing role assignments id (ra.id) as unique field, you can use $fields param for it.<ul style="text-align: left" data-rel="backtrace"><li>line 4091 of /lib/accesslib.php: call to debugging()</li><li>line 106 of /grade/report/grade_breakdown/index.php: call to get_role_users()</li></ul> in /home/colin/prj/moodle/git/docs/lib/weblib.php on line 2924, referer: https://colin.moodledev-28.oit.umn.edu/course/view.php?id=2

According to the new error message coming from get_role_users, the function usage is incorrect in this plugin.

**Comment by rrusso** [comment]
Fixed in master.

**Comment by rrusso** [comment]
Nevermind. It's broken elsewhere as well.

**Comment by rrusso** [comment]
Ok now it's really fixed.

**Comment by colin-umn** [comment]
That was fast.  Thanks!

**Comment by rrusso** [comment]
Was a simple oversight. sorry for the problems.
